# Generated by Django 4.0.3 on 2022-03-31 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubadminTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('admin_password', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('country', models.CharField(choices=[('Ghana', 'Ghana'), ('Nigeria', 'Nigeria'), ('Cameroon', 'Cameroon'), ('Ivory Coast', 'Ivory Coast'), ('Togo', 'Togo')], max_length=1000)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('subadmin_password', models.CharField(blank=True, max_length=255, null=True)),
                ('admin_password', models.CharField(blank=True, max_length=255, null=True)),
                ('sponsortID', models.CharField(blank=True, max_length=255, null=True)),
                ('uplinerID', models.CharField(blank=True, max_length=255, null=True)),
                ('user_type', models.CharField(choices=[('IBA', 'IBA'), ('Customer', 'Customer')], default='IBA', max_length=1000)),
                ('my_position', models.CharField(choices=[('Left', 'Left'), ('right', 'right')], default='Left', max_length=1000)),
                ('my_left_child', models.CharField(choices=[('Left', 'Left'), ('right', 'right')], default='Left', max_length=1000)),
                ('my_right_child', models.CharField(choices=[('Left', 'Left'), ('right', 'right')], default='Left', max_length=1000)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.IntegerField(blank=True, default=0, help_text='Personal Phone', null=True)),
                ('tel_fixe', models.IntegerField(blank=True, default=0, help_text='Fixed Line', null=True)),
                ('address', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(choices=[('Ghana', 'Ghana'), ('Nigeria', 'Nigeria'), ('Cameroon', 'Cameroon'), ('Ivory Coast', 'Ivory Coast'), ('Togo', 'Togo')], max_length=1000)),
                ('bank_name', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_branch_name', models.CharField(blank=True, max_length=20, null=True)),
                ('account_name', models.CharField(blank=True, max_length=20, null=True)),
                ('account_number', models.IntegerField(blank=True, default=0, help_text='Personal Phone', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL)),
                ('my_subadmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='apps_user_accounts.subadmintable')),
            ],
            managers=[
                ('clients', django.db.models.manager.Manager()),
            ],
        ),
    ]
