# Generated by Django 4.0.3 on 2022-04-01 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientstable',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientstable',
            name='national_id_card_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subadmintable',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientstable',
            name='my_subadmin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mysubadmin', to='apps_user_accounts.subadmintable'),
        ),
    ]
