# Generated by Django 4.0.3 on 2022-04-01 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network_settings', '0004_product_retailcommission_referralcommission_and_more'),
        ('apps_user_accounts', '0002_clientstable_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCommissionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_token_id', models.CharField(max_length=255, unique=True)),
                ('pv_assigned_to_upliner', models.IntegerField(help_text='corresponding e-pin')),
                ('activation_profit', models.IntegerField(blank=True, help_text='activation profit', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('downliner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iba_giving_bonus', to='apps_user_accounts.clientstable')),
                ('iba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iba_receiving_bonus', to='apps_user_accounts.clientstable')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_com_pack', to='network_settings.packages')),
                ('referral_commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_com_t', to='network_settings.referralcommission')),
            ],
        ),
        migrations.CreateModel(
            name='ActivationCommissionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_token_id', models.CharField(max_length=255, unique=True)),
                ('country', models.CharField(blank=True, max_length=1000, null=True)),
                ('activation_profit', models.IntegerField(blank=True, help_text='activation profit', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('activ_commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activate_com_t', to='network_settings.activationcommission')),
                ('activation_epin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activation_epins', to='network_settings.epins')),
                ('iba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iba_client', to='apps_user_accounts.clientstable')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activ_com_pack', to='network_settings.packages')),
            ],
        ),
    ]
