# Generated by Django 4.0.3 on 2022-04-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_settings', '0002_alter_epins_used_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='naira_amount',
            field=models.IntegerField(blank=True, default=0, help_text='Naira Amount attached', null=True),
        ),
    ]
