# Generated by Django 4.0.3 on 2022-04-01 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network_settings', '0003_alter_packages_naira_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('wholesale_price', models.IntegerField(blank=True, choices=[('132.00', '132.00'), ('263.00', '263.00'), ('1,050.00', '1,050.00')], help_text='Proce sold by company', null=True)),
                ('retail_price', models.IntegerField(blank=True, choices=[('172.00', '172.00'), ('342.00', '342.00'), ('1,365.00', '1,365.00')], help_text='retail price', null=True)),
                ('available_quantity', models.IntegerField(blank=True, default=0, help_text='total quantity of this articles', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RetailCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retail_name', models.CharField(max_length=255, unique=True)),
                ('product_quantity', models.IntegerField(blank=True, default=0, help_text='Percentage', null=True)),
                ('percentage', models.IntegerField(blank=True, default=0, help_text='Percentage', null=True)),
                ('condition', models.CharField(max_length=255, unique=True)),
                ('reward', models.CharField(max_length=255, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('bonus_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_plan_retail', to='network_settings.compensationplan')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_name', models.CharField(max_length=255, unique=True)),
                ('percentage', models.IntegerField(blank=True, default=0, help_text='Percentage', null=True)),
                ('condition', models.CharField(max_length=255, unique=True)),
                ('reward', models.CharField(max_length=255, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('bonus_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_plan_referral', to='network_settings.compensationplan')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_referral_com', to='network_settings.packages')),
            ],
        ),
        migrations.CreateModel(
            name='ActivationCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_name', models.CharField(max_length=255, unique=True)),
                ('product_quantity', models.IntegerField(blank=True, default=0, help_text='Percentage', null=True)),
                ('percentage', models.IntegerField(blank=True, default=0, help_text='Percentage', null=True)),
                ('condition', models.CharField(max_length=255, unique=True)),
                ('reward', models.CharField(max_length=255, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('bonus_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_plan_activation', to='network_settings.compensationplan')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_activation_com', to='network_settings.packages')),
            ],
        ),
    ]
